trigger:
  branches:
    include:
      - main

# Use your own self-hosted agent pool (Default pool by default)
pool:
  name: 'Default'   # 👈 this points to your Mac agent pool

variables:
  imageName: 'maven-hello-app'

stages:
  - stage: Build
    displayName: "Build Maven App"
    jobs:
      - job: MavenBuild
        displayName: "Maven Build & Test"
        steps:
          - task: Maven@3
            displayName: "Build with Maven"
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              javaHomeOption: 'Path'
              jdkDirectory: '/usr/local/opt/openjdk@17'   # adjust if JAVA_HOME differs
              mavenVersionOption: 'Default'

          - task: PublishBuildArtifacts@1
            displayName: "Publish JAR Artifact"
            inputs:
              PathtoPublish: 'target/*.jar'
              ArtifactName: 'drop'

  - stage: DockerBuild
    displayName: "Docker Build & Push"
    dependsOn: Build
    jobs:
      - job: BuildAndPush
        displayName: "Build Docker Image and Push to ACR"
        pool:
          name: 'Default'   # 👈 ensure Docker runs on your Mac agent
        steps:
          - task: Docker@2
            displayName: "Build and Push image to ACR"
            inputs:
              command: buildAndPush
              repository: $(imageName)
              dockerfile: '**/Dockerfile'
              containerRegistry: 'acr-connection'
              tags: |
                $(Build.BuildId)
                latest
