trigger:
  branches:
    include:
      - main

# Use your own self-hosted agent pool (Default pool by default)
pool:
  name: 'Default'   # 👈 this points to your Mac agent pool

variables:
  imageName: 'maven-hello-app'

stages:
  - stage: Build
    displayName: "Build Maven App"
    jobs:
      - job: MavenBuild
        displayName: "Maven Build & Test"
        steps:
          - task: Maven@3
            displayName: "Build with Maven"
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              javaHomeOption: 'Path'
              jdkDirectory: '/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home'   # adjust if JAVA_HOME differs
              mavenVersionOption: 'Default'

          - script: |
              echo "Sources dir: $(Build.SourcesDirectory)"
              echo "Default working dir: $(System.DefaultWorkingDirectory)"
              echo "Listing target folder..."
              ls -lh $(Build.SourcesDirectory)/target || true
              ls -lh $(System.DefaultWorkingDirectory)/target || true
            displayName: "Debug: Where is target?"
          - task: PublishBuildArtifacts@1
            displayName: "Publish JAR Artifact"
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
              ArtifactName: 'drop'

  - stage: DockerBuild
    displayName: "Docker Build & Push"
    dependsOn: Build
    jobs:
      - job: BuildAndPush
        displayName: "Build Docker Image and Push to ACR"
        pool:
          name: 'Default'   # 👈 ensure Docker runs on your Mac agent
        steps:
          - task: Docker@2
            displayName: "Build and Push image to ACR"
            inputs:
              command: buildAndPush
              repository: $(imageName)
              dockerfile: '**/Dockerfile'
              containerRegistry: 'acr-connection'
              tags: |
                $(Build.BuildId)
                latest
          - task: Maven@3
            displayName: "Use JAVA HOME default"
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: 'default'    # 👈 tells agent to use whatever JDK is already installed
              mavenVersionOption: 'Default'
